FROM node:14-alpine

# Create app directory
WORKDIR /src

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install -g nodemon && npm install
# If you are building your code for production
# RUN npm ci --omit=dev

# Bundle app source
EXPOSE 3000
COPY . /
CMD ["nodemon", "server.js"]